### ISSUE TITLE
Implement standard mySociety footer on collideosco.pe

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/collideoscope#1]
Moving across from mysociety/sysadmin#676 which discusses more prominent branding across all of our sites as a way of making their provenance clear.

**Comment by BenJam** [comment]
just looking at this @markcridge: collideoscope is a partnership and the footer currently on the site represents this.

**Comment by markcridge** [comment]
I think we have a version of the footer that caters to partnerships and
allows joint branding.

Can we look in to that please?

**Comment by davea** [comment]
Done in mysociety/fixmystreet@da000e5a09b1d95ad09eaea0b0439390f55b136a and deployed to [collideosco.pe](http://collideosco.pe/).
