### ISSUE TITLE
Update messaging to make site purpose clearer

### ISSUE THREAD

**Issue by zarino** [mysociety/collideoscope#11]
As a cyclist, I want to know that Collideoscope is the best way to take a collision or near miss that I’ve experienced, and turn it into a positive action for my local cycling community, by sending it to the local council, and contributing to a dataset used by cycling campaigners across the UK – so that I feel encouraged to report collisions and near misses I experience.

As a cycling campaigner, I want to know that Collideoscope will provide me with free, detailed data on collisions and near misses in my area, so that I can use it to back up my case when talking to local decision makers.

As a safety officer in a local council, I want to know how to receive the reports that Collideoscope collects for my area.

**Comment by MyfanwyNixon** [comment]
I've started to do some thinking around the report-making /confirmation copy. Lots of questions and comments, so input is welcome.

https://docs.google.com/document/d/1vpkMGwCjUUfN4DU83YJBOzc96Rc7dRgFFLHuIZ1snpc/edit#

Also speaks to #12 and has bearing on #15 .

**Comment by dracos** [comment]
Home page is under #34, assume being dealt with there. All changes from second doc either made, or comments made on the appropriate feature tickets/PRs for implementation there.
