### ISSUE TITLE
Collect responsiveness data in follow-up questionnaire

### ISSUE THREAD

**Issue by zarino** [mysociety/collideoscope#16]
As a cycle campaigner, I want to know how many Collideoscope incidents are reported to the police, and how many are eventually responded to by the police, so that I can investigate when/how the police respond, and what we can do to make sure cyclists complaints don’t get ignored.

---

Suggestion that we perhaps just _collect_ this data for now, and don’t yet _display_ it to anyone, while we work out the best way to present it in a constructive manner.

**Comment by dracos** [comment]
I think this needs a bit more detail. There's how long after report do we send follow-up (currently we send no followup); what question does it ask (sounds like it should be "did you report this to the police?" and "if so, did you hear back?" but not sure).

**Comment by dracos** [comment]
Yeah, linking to a page would be easier. "Have you heard back from {{ report.body }} about this report?" - I guess question is do we expect this? Not sure what councils are doing with these reports, if anything, do we think they should be. Should this email be sent only to the `report.involved_vehicle and report.involved_injury` people, perhaps, and only ask about police response?

**Comment by dracos** [comment]
I'm wondering, given those questions aren't what FMS currently handles at all (which is a question about changing state, and an asked-once-only question about reporting before), whether we use FMS to send questionnaire, but link is to a surveygizmo/monkey/googleform, prefilled. e.g. Here's a Google form I rustled up, Yes link:
https://docs.google.com/forms/d/e/1FAIpQLSecD2c6D1fQJs-BkyBl6S10REWcsqqLofuMyjWS0E6Kw8Nw9A/viewform?entry.1353964111=Yes&entry.143479696=123456&fbzx=-9218155286139353000
No link:
https://docs.google.com/forms/d/e/1FAIpQLSecD2c6D1fQJs-BkyBl6S10REWcsqqLofuMyjWS0E6Kw8Nw9A/viewform?entry.1353964111=No&entry.143479696=123456&fbzx=-9218155286139353000
What do you think?

**Comment by LouiseMySociety** [comment]
The email should still come from Collideoscope even if we do link to SurveyGizmo. However, if we decide to surface this data at a later stage the data isn't within Collideoscope. E.g Like we show the severity on the reports page.

**Comment by dracos** [comment]
It is easy to surface google forms data externally if that is desired.

**Comment by zarino** [comment]
Ok, so I’ve just chatted this over with @dracos.

He makes the good point that we don’t want to pressure councils into responding to each individual Collideoscope email they receive, because we know that’s unrealistic, and in some cases, we don’t even know whether the address we’ll be sending to is routinely staffed, or what. So collecting data about the responsiveness of councils might not be that useful.

Collecting data about how many people report vehicle+injury incidents to the police, though, and how many times they _then_ get a response from the police, is _much more interesting_ (to council safety teams, and eventually maybe even to third party researchers or campaigning orgs who want to fight under-reporting and police budget cuts).

So, I think we’re going with:

1. Questionnaire email to be sent out _only if_ incident involved a vehicle and an injury.
1. Questionnaire email will link to a SurveyGizmo form (since we use that for all our other forms/surveys), passing in the FMS report ID, so we can link up the response with the FMS report eventually, if we want.
1. Questionnaire asks whether they reported their incident to the police…
1. …And if they _did_ report it, whether they got a response.

I think that’s it?

**Comment by LouiseMySociety** [comment]
- [ ] @zarino to create survey in Gizmo Survey

**Comment by dracos** [comment]
Have started a `questionnaire-hooking` branch for this

**Comment by zarino** [comment]
#72 has been merged, so now a link to the SurveyGizmo survey will be sent out to reporters. :+1:
