### ISSUE TITLE
Ward and constituency level statistics

### ISSUE THREAD

**Issue by zarino** [mysociety/collideoscope#17]
As a cycling campaigner, I want to quickly and easily browse collision and near-miss statistics for a given council ward or parliamentary constituency, so that I can use them when talking to local councillors or MPs.

**Comment by zarino** [comment]
So the plan for this is to replace the current `/reports` page (which just shows a table of the total reports in various states per council) with something more similar to the dynamic filtering/grouping of fixmystreet.com/dashboard, but re-using the general layout of fixmystreet.com/reports. If that makes sense!

### Content

Text intro: Cyclists all over the UK contribute to Collideoscope’s database of cycling incidents and near misses. You can use the filters on this page to explore the data for the whole UK, a specific area, or a particular time range. And you can download the data currently on view as a CSV, for your own use. Just bear in mind, Collideoscope relies on user-submitted reports, so you shouldn’t use it to compare the absolute safety of different areas.

"Filter the data on this page by": area (default: all UK) / start date (default: earliest stats19 date?) / end date (default: today) / include data from STATS19 (default: include)

Line graph: total reports over selected time range

Button: Download a CSV of this data (produces a CSV of all the reports that match the current page filter, with columns straight from the DB)

"Show reports in your area": search/select box for map of council / ward / police area, which takes you to the specified `/reports/<area>` map page

Bar chart: total reports, by severity (near misses / bruises and scrapes / serious injury / fatality)

Bar chart: total reports, by transport mode (car, motorcycle, hgv, other vehicle, bike, pedestrian, nothing)

### Layout

```
+-------------------------+
|Text intro               |
+-------------------------+
|Filters                  |
+-------------------------+
|Line graph               |
|                         |
+-------------------------+
|Download   |Area search  |
|           |             |
+-------------------------+
|Bar chart:  Bar chart:   |
|Severity    Mode         |
+-------------------------+
```

I’ll try to get a static HTML version put together today, so we can start working out how to wire it up with real data.

**Comment by struan** [comment]
I am unclear on what area is supposed to be filtering on. Is it councils or something larger?

**Comment by dracos** [comment]
I'd say the box does what it does on /reports, so council lookup taking you to map page as now.
The filter at the top should be council, and then on the results page change to ward as /dashboard does now. That'll do for first pass anyway :)

**Comment by LouiseMySociety** [comment]
- [ ] Style filter by severity bar chart

**Comment by zarino** [comment]
#61 now includes a fix for the "find" instead of "pick" wording change.
