### ISSUE TITLE
Filter statistics by transport mode(s) involved: eg cyclists and HGVs

### ISSUE THREAD

**Issue by zarino** [mysociety/collideoscope#18]
As a cycling campaigner, I want to quickly extract statistics for collisions and near-misses involving particular transport modes, such as HGVs, so that I can use them as part of my mode-specific campaigns.

**Comment by struan** [comment]
The stats19 data doesn't have vehicle data so I'm not sure how useful filtering on that is going to be.

**Comment by dracos** [comment]
Stats19 does have it, we don't import it (apart from in textual detail, and partly in category). We could import it, but querying it would be slow, I imagine; could calculate top-level (overall + per-council) offline perhaps, but perhaps a different approach is needed, see #62
