### ISSUE TITLE
Download statistics as CSV

### ISSUE THREAD

**Issue by zarino** [mysociety/collideoscope#19]
As a cycling campaigner, once I’ve filtered my statistics (see #17, #18), I want to download the statistics as a CSV, so that I can make charts or graphs to include in my campaigning materials.

**Comment by LouiseMySociety** [comment]
This should be visible on this page: https://www.collideoscope.org.uk/reports . Zarino is on hand for design work should you need it.  This should work similar to the way FMS.com works.
