### ISSUE TITLE
Remove public updates

### ISSUE THREAD

**Issue by zarino** [mysociety/collideoscope#20]
As a police officer, I do not want the general public to be able to leave comments on Collideoscope reports, so that there is less chance of my witnesses being influenced, or magistrates discounting evidence in court.

As a cyclist who’s reported an incident on Collideoscope, I want to be able to leave updates, so that I can correct things I got wrong in my original report.

**Comment by davea** [comment]
Given the ticket title, I'm going to assume the first of these two conflicting user stories is the one we're implementing. Shout if that's not the right thing to do!

**Comment by zarino** [comment]
@davea you assumed right!

I had the second user story in there to make us think about whether there were _other_ ways we could solve that problem, if we went ahead an removed updates.

I’ve opened a new ticket for that: #30.

**Comment by zarino** [comment]
Mmmhmm. Another option that was suggested at the time was only allowing updates from the author of the report.

That would cut down on the potential for flame wars or speculation, but would still leave it open for a report author to return with a follow-up months later.

**Comment by LouiseMySociety** [comment]
Spoke to Zarino and agreed that the original author should be allowed to provide updates and these updates should be displayed publically

**Comment by davea** [comment]
I've updated #29 to only allow original problem reporters to leave updates.

**Comment by dracos** [comment]
Do we want to show a message to the user if not logged in to let them know they could add an update if they are the reporter and log in?

**Comment by dracos** [comment]
For the update bit - is that a design task for making the "Please note that updates are not sent to the highways department" text that is currently displayed bigger (it is tiny!) or is there more to it?
