### ISSUE TITLE
Import 2014–2017 STATS19 data

### ISSUE THREAD

**Issue by zarino** [mysociety/collideoscope#21]
As a cycle campaigner, I want to see recent STATS19 data on Collideoscope, so that I can use Collideoscope to see official reports and user-submitted reports, rather than having to wrangle the STATS19 data myself.

As a council safety officer, I want to see recent STATS19 data on Collideoscope, so that I know the site is being maintained, and the information on there is up-to-date and trustworthy.

**Comment by dracos** [comment]
Also links/see: 
https://github.com/mysociety/fixmystreet-commercial/issues/740
https://github.com/mysociety/fixmystreet-commercial/issues/741
