### ISSUE TITLE
Allow council staff to customise the content of the automatic confirmation emails

### ISSUE THREAD

**Issue by zarino** [mysociety/collideoscope#24]
Builds on #15.

As a council safety officer, I want to customise the text Collideoscope sends in its confirmation emails, so that we can better manage reporters’ expectations, and be sure the emails always reflect the latest work we’re doing.

**Comment by LouiseMySociety** [comment]
Potentially look at reusing some of the FMS Response Templates functionality.

Users would need a login and the ability to edit the templates that their council is responsible for.

**Comment by LouiseMySociety** [comment]
Potentially look at reviewing the existing email messages first (send to Myf to review?)

**Comment by dracos** [comment]
> Have your say in Collideoscope
> Tell us what you’d like our users to see when they submit a report within [% bodies_name %] -- we can edit confirmation text on a council by council basis, to manage customer expectations and best reflect  your working practices.

**Comment by dracos** [comment]
Could potentially become a Pro tool for councils to customise messages in emails.

**Comment by LouiseMySociety** [comment]
Agreed as a team that is a large piece of work for a small output and that our efforts should be focused elsewhere on the project.
