### ISSUE TITLE
Option to display "heat map" of incidents, rather than pins

### ISSUE THREAD

**Issue by zarino** [mysociety/collideoscope#25]
As a council safety officer, I want to search for a location and then see which roads or intersections there are the most dangerous, so that I can factor those areas into my safety reports and recommendations.

---

Google Maps does this _really nicely_ with their traffic estimates:

![screen shot 2018-08-02 at 15 12 39](https://user-images.githubusercontent.com/739624/43589405-8625ceda-9666-11e8-8be6-27f640f3d416.png)

I’m guessing this would be hard for us to replicate, without the underlying road vector data. But I figured it was worth mentioning!

**Comment by davea** [comment]
[This blog post](
https://anitagraser.com/2016/10/09/movement-data-in-gis-2-visualization/) outlines a mechanism for calculating styles on a per-segment basis in QGIS - might be useful as a starting point for further exploration:

![image](https://user-images.githubusercontent.com/4776/43590444-e709f85a-9668-11e8-8a54-aaac50b78705.png)

**Comment by davea** [comment]
A bit of fiddling around in QGIS results in this:

![layout 2](https://user-images.githubusercontent.com/4776/44045016-4586216a-9f1f-11e8-9a18-bddecf307671.png)

(aside, this really makes cycling in London look _fun_)

This was using the Collideoscope/Stats19 reports to date, on top of OS road data. So in principle it's possible.

**Comment by davea** [comment]
![Heatmap screenshot](https://user-images.githubusercontent.com/4776/45749260-020b0300-bc03-11e8-87b1-284bf30ee50d.png)

Done and deployed.

**Comment by davea** [comment]
The code for this is in [mysociety/collideoscope-heatmap](https://github.com/mysociety/collideoscope-heatmap).
