### ISSUE TITLE
Homepage “panic button” on mobile view

### ISSUE THREAD

**Issue by zarino** [mysociety/collideoscope#27]
As a cyclist who’s literally just had an accident or a near miss, I want to be able to tell Collideoscope something just happened, and have it remind me to fill in the details later, so that I can get on with my report when I’m less flustered.

---

This was a bit of a "nice to have" that came up during user research. It’d mean:

* A big button on the homepage (on mobile only) that starts a "draft" report (assuming you’re logged in?) with the device’s current location and time.
* An email follow-up that gives them a link to fill in the full report details whenever’s convenient for them.

**Comment by LouiseMySociety** [comment]
@struan has completed the code for this, it now needs styling.
