### ISSUE TITLE
Let me edit my own reports

### ISSUE THREAD

**Issue by zarino** [mysociety/collideoscope#30]
Spun out from #20.

> As a cyclist who’s reported an incident on Collideoscope, I want to be able to leave updates, so that I can correct things I got wrong in my original report.

It looks like a common reason for leaving "Updates" on reports is simply to correct mistakes in the original, because FMS gives report authors no way to amend their report title or text after it’s been submitted.

Using updates for this seems kinda messy, since we could _just allow_ users to edit their own reports. I’m assuming it could use the exact same "moderation" logic that site admins already have access to.

**Comment by davea** [comment]
Do we have a rough idea how long it takes users to leave their amendment updates after making the original report? The thing about allowing users to edit reports is that their edits won't be sent to the council.

One option might be to re-send the report after it's been edited but that's not ideal as it might increase the perceived noise from the site, cause council officers to re-key everything *again*, or even ignore reports in anticipation of a correction arriving shortly after.

If we allowed a grace period of, say, an hour before the report is sent it would allow users a chance to see their report on the site and make any adjustments. But getting the length of that period correct would be key as we wouldn't want to make the site seem slow (especially if we're letting the user know via email once their report has actually be sent, i.e. #15).

**Comment by zarino** [comment]
@davea The reason this has been brought up in a Collideoscope context (rather than an FMS one) is that at least on Collideoscope, the reports are more _informational_ and less _transactional_. If corrections don’t make it to the council, it won’t be the end of the world. The emails aren’t _immediately_ acted on, they’re more for the council’s _general information_, and an opportunity for someone from the council to contact the cyclist if it was a particularly bad incident.

It’s also _no worse_ than what we already do (where the council never recieves the "updates" anyway!) and the corrected report details will all be there online if the council (or anybody else!) comes to check them – which sounds like it’ll be the primary way they’ll use Collideoscope as part of their decision-making processes.

Which is all a long way of saying: On Collideoscope, I don’t think it’ll be a big problem if the original email sent to the council contains mistakes.

**Comment by davea** [comment]
> On Collideoscope, I don’t think it’ll be a big problem if the original email sent to the council contains mistakes.

Lovely, that keeps things simple then.

You're right that we can probably build on the moderation tools for this feature 👍

**Comment by LouiseMySociety** [comment]
Spoke to Zarino and agreed on Dave's point above. If an edit is made, this will not send the council an additional email. 

Do we show the option to edit only to logged in users?

**Comment by dracos** [comment]
Given #20 has changed to allow updates from the original reporter, do we still want this? Guess still might be useful. Anyway, steps involved:
- [ ] Add ability for a cobrand to always set moderate permission if viewing own report (a cobrand hook to override user permissions? But needs access to report ID, hmm. Perhaps needs its own permission lookup, with override);
- [ ] Allow Moderate.pm to pass current staff-only checks

Think that's it, current form asks for 'reason' which I could see not being wanted but can leave in first pass.

**Comment by dracos** [comment]
No title moderation should be at #68 and https://github.com/mysociety/fixmystreet/pull/2228

**Comment by zarino** [comment]
#68 and https://github.com/mysociety/fixmystreet/pull/2228 have been merged, and work as described.

It feels like we could make the UI a bit friendlier though, if we know that you’re logged in as the author of the report:

- [ ] Button could be labelled "Edit" or "Edit this report" rather than "Moderate"
- [ ] "Show my name" checkbox, rather than "Show reporter’s name"
- [ ] "Describe why you’re moderating this" feels like overkill for a user self-editing their report – I suggest we hide it, and either leave it empty or pre-fill it with something generic.

I’ll add these to my list for today/Monday.

@dracos I take it, it’s a Hard problem to make the report metadata (like `severity` or `participants`) editable too?

**Comment by dracos** [comment]
Without having to override `_main.html` (want to try and avoid that), you can do the first two with the locale script `bin/make_po`, and the third with CSS to hide it (think it's optional anyway).
Making the metadata editable - if you weren't concerned about keeping original (as it does for title/detail), then it wouldn't be that much work, no, form stuff is only updating the template here to have the edit bits (as with the title/detail in core), then server side would need another cobrand hook to do extra cobrand moderation (or a generic 'take in any moderation fields on extra paramaters' perhap).

**Comment by zarino** [comment]
@dracos "Show my name" if you were the reporter seems like a change we could just make in core anyway, no? "Edit" rather than "Moderate"… I’m almost tempted to say the same, unless we think it might be confusing for council staff who would now see an "Edit" button rather a "Moderate" button, for reports they’ve made themselves and are then having to moderate? But I wonder how often that happens?

**Comment by dracos** [comment]
> "Show my name" if you were the reporter seems like a change we could just make in core anyway, no?
Reporters can't edit their own reports in core, this is this cobrand only. I don't think we want to change Moderate, no, based on the training I've given.
