### ISSUE TITLE
Make police boundary data available via MapIt

### ISSUE THREAD

**Issue by davea** [mysociety/collideoscope#41]
This would enable reporting statistics for police forces, sign post users to the right force for their report (see #13), etc.

**Comment by davea** [comment]
I've imported the 2016 shapefiles from [data.gov.uk](https://data.gov.uk/dataset/c3f81705-fb42-4e3d-a8eb-3cf374d61a63/police-force-areas-december-2016-full-extent-boundaries-in-england-and-wales) to a [dev MapIt](http://davea.mapit.dev.mysociety.org/), e.g. http://davea.mapit.dev.mysociety.org/areas/POL.map.html

bbcda0b29586a7fb50b22ed0d3999be7488dbd9b updates the report confirmation screen to include the correct name of the police force in question, along with a link to that force's reporting page.

**Comment by dracos** [comment]
Superseded by using police API
