### ISSUE TITLE
Mobile: Clearer calls to action

### ISSUE THREAD

**Issue by LouiseMySociety** [mysociety/collideoscope#43]
Make the  'Support us' and  'Contact us' links clearer calls to action

**Comment by dracos** [comment]
The main text for "Interested in safer cycling?" says "We're looking for supporters" which is why "Support us" is after it? I mean, it could be clearer it's a call to action rather than another heading (look different/ aligned right/ whatever), but the order seems to make sense?

**Comment by LouiseMySociety** [comment]
@dracos I think you're right, a better call to action might be clearer then as I think the text gets a bit lost when it's on mobile.  I'll edit the ticket the description to match this.

**Comment by dracos** [comment]
Note #51 current removes this text, though not sure if going with replacement testimonials...
