### ISSUE TITLE
Potential integration with cycling campaign groups

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/collideoscope#49]
One of the suggested actions in the text of the confirmation email is:
>Consider getting in touch with your local campaign group to help work towards safer road conditions for cyclists.

A trivial addition to this would be a link to eg http://www.cyclenation.org.uk/groups and https://www.cyclinguk.org/groups-listing?geo%5Bdistance%5D=40&geo%5Bunit%5D=3959&geo%5Borigin%5D=&title=&field_group_activities_value=CAMP&field_group_type_value=All (long URL cos filtered for campaigning activities).

And a more complex addition maybe to consider in the future, would be to link directly to the local campaigning group based on what we know about the report-maker's postcode (although incidents don't always happen in one's area of residence, I suppose).

**Comment by zarino** [comment]
This was fixed as part of 6c35361784e0255f309007776799893d279fb181.

If you report a near miss with a vehicle, or an incident not involving a vehicle (ie: something that doesn’t require reporting to the police) then we show:

> You can also take a hand in making your own local roads safer by [joining your local cycling campaign](https://www.cyclinguk.org/groups-listing).
